### ISSUE TITLE
chrome extension stopped working on 2015-05-13

### ISSUE THREAD

**Issue by phpmoli** [xisberto/phonetodesktop#17]
Dear Humberto,
Please take a look at these bug reports in the chrome web store: https://chrome.google.com/webstore/detail/phone-to-desktop/oifdfchgmkfglcccmkoofhbnmkdlbgag/support
Thank you!

**Comment by xisberto** [comment]
Thank you for the report!

The new version is uploaded to the Chrome Store and should be updated ina few hours.
