### ISSUE TITLE
app traffic feels a lot compared to it is handling text-only

### ISSUE THREAD

**Issue by phpmoli** [xisberto/phonetodesktop#22]
Dear Humberto,

Is it normal for the app to eat this much traffic in a 8 hour workday while i am at work (gross, including travelling, still 10 hours max.) ?

Is it communicating by GCM messages or by pull with constantly querying? If the latter, could the user configure the time frequency? Like I myself would be content with a 15 minute freq and the option to manually do it by pressing the "view wait list" button.

Thanks.

This is 1 day's traffic, not a whole month's. Installed Opera Max on aug-20, used P2D on aug-22, captured the screenshot on aug-22.

![screenshot_2016-08-22-20-31-55_com opera max global](https://cloud.githubusercontent.com/assets/5528385/18068649/b5290a92-6e42-11e6-8c6d-3fc52351e26d.png)

**Comment by xisberto** [comment]
The current version of Phone to Desktop doesn't use GCM nor does any constant query. It only communicates with Google services when you interacts with it.

Also, using a third party app to measure data isn't reliable. Android has it own mobile data meter, that you can see under the app info.

That said, it also depends on how much data you have saved on your Google Tasks. Phone to Desktop will download the entire list it created when you open the "Sent texts" screen.

**Comment by phpmoli** [comment]
Dear @xisberto , I had lots of completed tasks in the task list, which are downloaded at every refresh but not shown in the app, so probably that was my cause. I had deleted my completed tasks, hope this will resolve this problem, thank you.
