### ISSUE TITLE
Q: When a link is sent, could it be auto-opened in a desktop tab?

### ISSUE THREAD

**Issue by Wizek** [xisberto/phonetodesktop#23]

**Comment by Wizek** [comment]
cc @xisberto in case you would have wanted to get notified of this and weren't.

**Comment by humbertofraga** [comment]
There's currently no plans to further update this app.
The auto-open feature would depend on the extension constantly checking the Google Tasks service for new links, and this would require that:

1. Me, as the publisher, to request Google for larger limits on the API usage, or
2. Including on the code instructions for creating a Google API Console project and obtaining the app keys for users wanting this functionality.

Neither option is good for me. As the license allows it, others can fork the project, host it on its own Google Console keys and implement those features.

**Comment by Wizek** [comment]
Ah, I see, that's a bummer that this would require polling. I was guessing/hoping that this was based on GCN ([Google Cloud Messaging](https://developers.google.com/cloud-messaging/gcm)) or similar; relying on push events without polling. Understandable this way.
